#!/bin/bash

# Check if eth0 is assigned any ip 
# Display the notification in gnome using pynotify 
# Kish 


out=`/sbin/ifconfig eth0|grep "inet addr"`
if [[ $? -eq 0 ]]; then 
	STAT="\" connected \"" 
    else
        STAT="\"not connected\" "
fi 

python2 <<STUFF

import pynotify

pynotify.init("Eth0 status")
msg = pynotify.Notification("ifconfig eth0", ${STAT}, "dialog-alert")
msg.set_timeout(pynotify.EXPIRES_DEFAULT)
msg.show()
STUFF

